on: [push,pull_request]

jobs:
  main_job:
    runs-on: ubuntu-latest
    name: Solidity Security 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM Install
        run: npm i
      - name: solidity
        run: brew install solidity
      - name: slither
        run: pip3 install slither-analyzer
      - name: DFY.sol
        run: slither contracts/DFYtoken/DFY.sol
      - name: ERC20CustomToken.Sol
        run: slither contracts/DFYtoken/ERC20CustomToken.sol
      - name: DFYTreasure.sol
        run: slither contracts/DFYtoken/DFYTreasure.sol
      - name: DFY-1155.sol
        run: slither contracts/NFT/DFY-1155.sol
      - name: AdminUpgradeabilityProxy.sol
        run: slither contracts/pawn/AdminUpgradeabilityProxy.sol
      - name: PawnContract.sol
        run: slither contracts/pawn/PawnContract.sol
      - name: IdoDFY.sol
        run: slither contracts/IDO/IdoDFY.sol
      - name: Staking.sol
        run: slither contracts/staking/Staking.sol


