on: [push,pull_request]

jobs:
  main_job:
    runs-on: ubuntu-latest
    name: Solidity Security 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: solidity
        run: brew install solidity
      - name: slither
        run: pip3 install slither-analyzer
